//
// Generated by JTB 1.2.2
//

package util.parser.java.v14.nodes;

/**
 * Grammar production:
 * f0 -> VariableDeclaratorId()
 * f1 -> [ "=" VariableInitializer() ]
 */
public class VariableDeclarator implements Node {
   public VariableDeclaratorId f0;
   public NodeOptional f1;

   public VariableDeclarator(VariableDeclaratorId n0, NodeOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(util.parser.java.v14.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v14.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

