//
// Generated by JTB 1.2.2
//

package util.parser.java.v14.nodes;

/**
 * Grammar production:
 * f0 -> [ "final" ]
 * f1 -> Type()
 * f2 -> VariableDeclaratorId()
 */
public class FormalParameter implements Node {
   public NodeOptional f0;
   public Type f1;
   public VariableDeclaratorId f2;

   public FormalParameter(NodeOptional n0, Type n1, VariableDeclaratorId n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public void accept(util.parser.java.v14.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v14.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

