//
// Generated by JTB 1.2.2
//

package util.parser.java.v14.nodes;

/**
 * Represents a grammar choice, e.g. ( A | B )
 */
public class NodeChoice implements Node {
   public NodeChoice(Node node) {
      this(node, -1);
   }

   public NodeChoice(Node node, int whichChoice) {
      choice = node;
      which = whichChoice;
   }

   public void accept(util.parser.java.v14.visitors.Visitor v) {
      choice.accept(v);
   }
   public Object accept(util.parser.java.v14.visitors.ObjectVisitor v, Object argu) {
      return choice.accept(v,argu);
   }

   public Node choice;
   public int which;
}

