//
// Generated by JTB 1.2.2
//

package util.parser.java.v14.nodes;

/**
 * Grammar production:
 * f0 -> "package"
 * f1 -> Name()
 * f2 -> ";"
 */
public class PackageDeclaration implements Node {
   public NodeToken f0;
   public Name f1;
   public NodeToken f2;

   public PackageDeclaration(NodeToken n0, Name n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public PackageDeclaration(Name n0) {
      f0 = new NodeToken("package");
      f1 = n0;
      f2 = new NodeToken(";");
   }

   public void accept(util.parser.java.v14.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v14.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

