//
// Generated by JTB 1.2.2
//

package util.parser.java.v14.nodes;

/**
 * Grammar production:
 * f0 -> PrimaryPrefix()
 * f1 -> ( PrimarySuffix() )*
 */
public class PrimaryExpression implements Node {
   public PrimaryPrefix f0;
   public NodeListOptional f1;

   public PrimaryExpression(PrimaryPrefix n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(util.parser.java.v14.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v14.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

