//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> "default"
 * f1 -> MemberValue()
 */
public class DefaultValue implements Node {
   public NodeToken f0;
   public MemberValue f1;

   public DefaultValue(NodeToken n0, MemberValue n1) {
      f0 = n0;
      f1 = n1;
   }

   public DefaultValue(MemberValue n0) {
      f0 = new NodeToken("default");
      f1 = n0;
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

