//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> "enum"
 * f1 -> <IDENTIFIER>
 * f2 -> [ ImplementsList(false) ]
 * f3 -> EnumBody()
 */
public class EnumDeclaration implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeOptional f2;
   public EnumBody f3;

   public EnumDeclaration(NodeToken n0, NodeToken n1, NodeOptional n2, EnumBody n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public EnumDeclaration(NodeToken n0, NodeOptional n1, EnumBody n2) {
      f0 = new NodeToken("enum");
      f1 = n0;
      f2 = n1;
      f3 = n2;
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

