//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> "@"
 * f1 -> Name()
 */
public class MarkerAnnotation implements Node {
   public NodeToken f0;
   public Name f1;

   public MarkerAnnotation(NodeToken n0, Name n1) {
      f0 = n0;
      f1 = n1;
   }

   public MarkerAnnotation(Name n0) {
      f0 = new NodeToken("@");
      f1 = n0;
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

