//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> Modifiers()
 * f1 -> "package"
 * f2 -> Name()
 * f3 -> ";"
 */
public class PackageDeclaration implements Node {
   public Modifiers f0;
   public NodeToken f1;
   public Name f2;
   public NodeToken f3;

   public PackageDeclaration(Modifiers n0, NodeToken n1, Name n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public PackageDeclaration(Modifiers n0, Name n1) {
      f0 = n0;
      f1 = new NodeToken("package");
      f2 = n1;
      f3 = new NodeToken(";");
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

