//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
">"
 * f0 -> ">"
 * f1 -> ">"
 */
public class RUNSIGNEDSHIFT implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeToken f2;

   public RUNSIGNEDSHIFT(NodeToken n0, NodeToken n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public RUNSIGNEDSHIFT() {
      f0 = new NodeToken(">");
      f1 = new NodeToken(">");
      f2 = new NodeToken(">");
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

