//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> "synchronized"
 * f1 -> "("
 * f2 -> Expression()
 * f3 -> ")"
 * f4 -> Block()
 */
public class SynchronizedStatement implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Expression f2;
   public NodeToken f3;
   public Block f4;

   public SynchronizedStatement(NodeToken n0, NodeToken n1, Expression n2, NodeToken n3, Block n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public SynchronizedStatement(Expression n0, Block n1) {
      f0 = new NodeToken("synchronized");
      f1 = new NodeToken("(");
      f2 = n0;
      f3 = new NodeToken(")");
      f4 = n1;
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

