//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> "<"
 * f1 -> TypeParameter()
 * f2 -> ( "," TypeParameter() )*
 * f3 -> ">"
 */
public class TypeParameters implements Node {
   public NodeToken f0;
   public TypeParameter f1;
   public NodeListOptional f2;
   public NodeToken f3;

   public TypeParameters(NodeToken n0, TypeParameter n1, NodeListOptional n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public TypeParameters(TypeParameter n0, NodeListOptional n1) {
      f0 = new NodeToken("<");
      f1 = n0;
      f2 = n1;
      f3 = new NodeToken(">");
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

