//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> "@"
 * f1 -> "interface"
 * f2 -> <IDENTIFIER>
 * f3 -> AnnotationTypeBody()
 */
public class AnnotationTypeDeclaration implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeToken f2;
   public AnnotationTypeBody f3;

   public AnnotationTypeDeclaration(NodeToken n0, NodeToken n1, NodeToken n2, AnnotationTypeBody n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public AnnotationTypeDeclaration(NodeToken n0, AnnotationTypeBody n1) {
      f0 = new NodeToken("@");
      f1 = new NodeToken("interface");
      f2 = n0;
      f3 = n1;
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

