//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> Modifiers()
 * f1 -> <IDENTIFIER>
 * f2 -> [ Arguments() ]
 * f3 -> [ ClassOrInterfaceBody(false) ]
 */
public class EnumConstant implements Node {
   public Modifiers f0;
   public NodeToken f1;
   public NodeOptional f2;
   public NodeOptional f3;

   public EnumConstant(Modifiers n0, NodeToken n1, NodeOptional n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

