//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> Modifiers()
 * f1 -> Type()
 * f2 -> [ "..." ]
 * f3 -> VariableDeclaratorId()
 */
public class FormalParameter implements Node {
   public Modifiers f0;
   public Type f1;
   public NodeOptional f2;
   public VariableDeclaratorId f3;

   public FormalParameter(Modifiers n0, Type n1, NodeOptional n2, VariableDeclaratorId n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

