//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> "implements"
 * f1 -> ClassOrInterfaceType()
 * f2 -> ( "," ClassOrInterfaceType() )*
 */
public class ImplementsList implements Node {
   public NodeToken f0;
   public ClassOrInterfaceType f1;
   public NodeListOptional f2;

   public ImplementsList(NodeToken n0, ClassOrInterfaceType n1, NodeListOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public ImplementsList(ClassOrInterfaceType n0, NodeListOptional n1) {
      f0 = new NodeToken("implements");
      f1 = n0;
      f2 = n1;
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

