//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> "."
 * f1 -> TypeArguments()
 * f2 -> <IDENTIFIER>
 */
public class MemberSelector implements Node {
   public NodeToken f0;
   public TypeArguments f1;
   public NodeToken f2;

   public MemberSelector(NodeToken n0, TypeArguments n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public MemberSelector(TypeArguments n0, NodeToken n1) {
      f0 = new NodeToken(".");
      f1 = n0;
      f2 = n1;
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

