//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> "@"
 * f1 -> Name()
 * f2 -> "("
 * f3 -> [ MemberValuePairs() ]
 * f4 -> ")"
 */
public class NormalAnnotation implements Node {
   public NodeToken f0;
   public Name f1;
   public NodeToken f2;
   public NodeOptional f3;
   public NodeToken f4;

   public NormalAnnotation(NodeToken n0, Name n1, NodeToken n2, NodeOptional n3, NodeToken n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public NormalAnnotation(Name n0, NodeOptional n1) {
      f0 = new NodeToken("@");
      f1 = n0;
      f2 = new NodeToken("(");
      f3 = n1;
      f4 = new NodeToken(")");
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

