//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> <IDENTIFIER>
 * f1 -> [ TypeBound() ]
 */
public class TypeParameter implements Node {
   public NodeToken f0;
   public NodeOptional f1;

   public TypeParameter(NodeToken n0, NodeOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

